baseURL = "https://james-becker.github.io/beckerweb/"
languageCode = "en-us"
title = "J. James Becker"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-hikari-theme"
publishDir = "docs"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  name = "J. James Becker"
  description = "Describe your website"
  copyright = "© J. James Becker"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/style-custom.css"]
  custom_js  = []

  # Links to newer/older blog posts
  newer = "Newer"
  older = "Older"

  pageNotFoundTitle = "Page not found"
  pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
  # Menu items
  title = "James Becker"
  bio = "James Becker is a writer, music producer, painter, elephant trainer and software developer residing in Bangkok, Thailand. Covered topics include technology, culture, philosophy, and Asia."

  subscribe = "Subscribe"
  followme = "Find me on"

  # Enable Google search
  search_enabled = true
  search = "Search"

  [[params.offcanvas.socialnetworks]]
    name = "Github"
    url = "//github.com/james-becker"

  [[params.offcanvas.socialnetworks]]
    name = "Twitter"
    url = "//twitter.com/spf13"
